<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pav</string>
	</array>
	<key>name</key>
	<string>Parva</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Numbers</string>
			<key>match</key>
			<string>(\d+)?(\.)?(\d+)</string>
			<key>name</key>
			<string>constant.numeric.pav</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keyword if</string>
			<key>match</key>
			<string>(\b)(true|false|null)(\b)</string>
			<key>name</key>
			<string>constant.numeric.pav</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Single line comments</string>
			<key>match</key>
			<string>//.*</string>
			<key>name</key>
			<string>comment.pav</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>In-line comments</string>
			<key>match</key>
			<string>(/\*)(.*)(\*/)</string>
			<key>name</key>
			<string>comment.pav</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>(\b)(if|while|for|else|do|goto|break|continue|const|return|halt|switch|case)(\b)</string>
			<key>name</key>
			<string>keyword.pav</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Support functions</string>
			<key>match</key>
			<string>(\b)(read|write)(\b)</string>
			<key>name</key>
			<string>support.function.pav</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.pav</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.pav</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Storage types with Functions</string>
			<key>match</key>
			<string>(\b)(int|bool|void)(\b)( \w*)(\W*\()</string>
			<key>name</key>
			<string>markup.pav</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.pav</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Storage types</string>
			<key>match</key>
			<string>(\b)(int|bool|const|void)(\b)</string>
			<key>name</key>
			<string>markup.pav</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.pav</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Function calls</string>
			<key>match</key>
			<string>(\b)(\w*)([ ]*\()</string>
			<key>name</key>
			<string>markup.pav</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>String Quotes</string>
			<key>match</key>
			<string>\"(.*?)[^\\]\"</string>
			<key>name</key>
			<string>string.pav</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Char Quotes</string>
			<key>match</key>
			<string>(\')(\\?.)(\')</string>
			<key>name</key>
			<string>string.pav</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.pav</string>
	<key>uuid</key>
	<string>4aa6b831-8d6c-4b2c-96f3-7a46d049f870</string>
</dict>
</plist>
